---
- hosts: all
  become: true

  vars:
    update_and_reboot: yes

  roles:
    - update

  tasks:
    - name: Install packages.
      yum:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - git
